steps:
- script: |
    if [[ $(rubyVersion) =~ 2\.[0-2]\.[0-9]+ ]]; then
      gem install bundler --no-document -v '<2'
    else
      gem install bundler --no-document
    fi
  displayName: 'gem install bundler'
- script: bundle install --retry=3 --jobs=4
  displayName: 'bundle install'
- script: bundle exec rake
  displayName: 'bundle exec rake'
