steps:
- script: |
    if [[ $(rubyVersion) =~ 2\.[0-2]\.[0-9]+ ]]; then
      $(gemBinPath)/gem install bundler --no-document -v '<2'
    else
      $(gemBinPath)/gem install bundler --no-document
    fi
  displayName: 'gem install bundler'
- script: |
    $(gemBinPath)/bundle install --retry=3 --jobs=4
  displayName: 'bundle install'
- script: |
    $(gemBinPath)/bundle exec $(gemBinPath)/rake
  displayName: 'bundle exec rake'
