steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: $(rubyVersion)
- script: |
    gem install bundler --no-document
  displayName: 'gem install bundler'
- script: |
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'
- script: |
    bundle exec rake
  displayName: 'bundle exec rake'
