inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  NewCops: enable

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'Gemfile'

Style/MutableConstant:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/spec_helper.rb'

Style/RedundantPercentQ:
  Enabled: false
