inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/spec_helper.rb'

Style/UnneededPercentQ:
  Enabled: false
