# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

jobs:
- job: Linux
  strategy:
    matrix:
      ruby23:
        ruby_version: '2.3'
      ruby24:
        ruby_version: '2.4'
      ruby25:
        ruby_version: '2.5'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: $(ruby_version)
  - template: azure-pipelines-templates/steps.yml

- job: macOS
  strategy:
    matrix:
      ruby26:
        ruby_version: '2.6.2'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      brew -v
      brew install rbenv
    displayName: 'brew install rbenv'
  - script: |
      echo -e '\neval "$(rbenv init -)"' >> ~/.bash_profile
    displayName: 'rbenv init'
  - script: |
      rbenv install $(ruby_version)
      rbenv local $(ruby_version)
      source ~/.bash_profile
      ruby -v
    displayName: 'rbenv install'
  - script: gem install bundler --no-document
    displayName: 'gem install bundler'
  - script: bundle install --retry=3 --jobs=4
    displayName: 'bundle install'
  - script: |
      which ruby
      which gem
      which rake
      which bundle
      bundle exec rake
    displayName: 'bundle exec rake'

- job: Windows
  strategy:
    matrix:
      ruby24:
        ruby_version: '2.4'
      ruby25:
        ruby_version: '2.5'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: $(ruby_version)
  - template: azure-pipelines-templates/steps.yml
