# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- main

jobs:
- job: 'ubuntu_1604'
  strategy:
    matrix:
      ruby20:
        rubyVersion: '2.0.0-p648'
      ruby21:
        rubyVersion: '2.1.10'
      ruby22:
        rubyVersion: '2.2.10'
      ruby23:
        rubyVersion: '2.3.8'
      ruby24:
        rubyVersion: '2.4.10'
      ruby25:
        rubyVersion: '2.5.8'
      ruby26:
        rubyVersion: '2.6.6'
      ruby27:
        rubyVersion: '2.7.2'
      ruby30:
        rubyVersion: '3.0.0'
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
  - name: libsslDev10PackageName
    value: libssl-dev=1.0.2g-1ubuntu4.18
  - name: rubyBuildBinPath
    value: ~/local/bin
  - name: gemBinPath
    value: ~/local/ruby-$(rubyVersion)/bin
  steps:
  - template: azure-pipelines-templates/steps-ubuntu.yml

- job: 'ubuntu_1804'
  strategy:
    matrix:
      ruby20:
        rubyVersion: '2.0.0-p648'
      ruby21:
        rubyVersion: '2.1.10'
      ruby22:
        rubyVersion: '2.2.10'
      ruby23:
        rubyVersion: '2.3.8'
      ruby24:
        rubyVersion: '2.4.10'
      ruby25:
        rubyVersion: '2.5.8'
      ruby26:
        rubyVersion: '2.6.6'
      ruby27:
        rubyVersion: '2.7.2'
      ruby30:
        rubyVersion: '3.0.0'
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
  - name: libsslDev10PackageName
    value: libssl1.0-dev
  - name: rubyBuildBinPath
    value: ~/local/bin
  - name: gemBinPath
    value: ~/local/ruby-$(rubyVersion)/bin
  steps:
  - template: azure-pipelines-templates/steps-ubuntu.yml

- job: macOS
  strategy:
    matrix:
      ruby20:
        rubyVersion: '2.0.0-p648'
      ruby21:
        rubyVersion: '2.1.10'
      ruby22:
        rubyVersion: '2.2.10'
      ruby23:
        rubyVersion: '2.3.8'
      ruby24:
        rubyVersion: '2.4.10'
      ruby25:
        rubyVersion: '2.5.8'
      ruby26:
        rubyVersion: '2.6.6'
      ruby27:
        rubyVersion: '2.7.2'
      ruby30:
        rubyVersion: '3.0.0'
  pool:
    vmImage: 'macOS-10.14'
  variables:
  - name: gemBinPath
    value: ~/ruby-$(rubyVersion)/bin
  steps:
  - template: azure-pipelines-templates/steps-macos.yml

- job: Windows
  strategy:
    matrix:
      ruby24:
        rubyVersion: '2.4'
      ruby25:
        rubyVersion: '2.5'
      ruby26:
        rubyVersion: '2.6'
      ruby27:
        rubyVersion: '2.7'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: azure-pipelines-templates/steps-windows.yml
